Driver company code vehicle check
Modubus/ModubusBackend pull request #9
Opened 2024-08-02 22:31 UTC by dania0x4C

2024-08-03 02:45 UTC, Jaehyeon1020 requested changes

2024-08-03 02:45 UTC, Jaehyeon1020 commented on Dockerfile
> +# RUN npm install
여기 왜 삭제됐는지 알 수 있을까요?

2024-08-03 02:45 UTC, Jaehyeon1020 commented on src/main.ts
> +dotenv.config({ path: '.env.development' })
원래대로 변경 필요해보입니다!

2024-08-03 02:54 UTC, dania0x4C commented on Dockerfile
> +# RUN npm install
아 제가 누르다가 실수로 삭제 된 것 같습니다

2024-08-06 07:01 UTC, Jaehyeon1020 requested changes
추가로, Merge conflict 해결 부탁드립니다

2024-08-06 07:01 UTC, Jaehyeon1020 commented on ModubusBackend
이 디렉토리는 왜 있는건지 알 수 있을까요?

2024-08-06 07:01 UTC, Jaehyeon1020 commented on src/user/user.service.ts
> +import * as bcrypt from 'bcryptjs'
bcryptjs가 계속 사용되는건가요?

2024-08-06 07:22 UTC, dania0x4C commented on src/user/user.service.ts
> +import * as bcrypt from 'bcryptjs'
이거는 일단 js를 사용하지 않으면 서버 사용시 충돌이 생겨서 안 되더라고요 기능적으로 다르지 않다고해서 변경했습니다!

2024-08-06 07:22 UTC, dania0x4C commented on ModubusBackend
아 이거는 실수로 만든건데 .gitignore에 넣어두었는데 왜 올라간지 모르겠네요...?

2024-08-06 07:23 UTC, dania0x4C commented on .vscode/settings.json
> +}
이거는 그냥 문자 워드 문법상 안 맞으면 오류가 생겨서 자동으로 없어지게 하다보니까 생겼고 기능상으로 문제가 생기지는 않지만 제거하겠습니다

2024-08-06 07:24 UTC, dania0x4C commented on prisma/schema.prisma
> +  cityCode String
알겠습니다

2024-08-06 07:26 UTC, dania0x4C commented on .eslintrc.js
> +    'prettier/prettier': ['error', { semi: false, endOfLine: 'auto' }],
이거 운체마다 줄끝 처리?가 다른데 그냥 자동으로 맞춰주는 코드입니다

2024-08-06 15:48 UTC, Jaehyeon1020 approved these changes

2024-08-06 15:49 UTC, merged